# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
