# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
