# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandmanager', '0002_auto_20161217_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
