# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandmanager', '0002_progressmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bandmanager.ProgressMapping'),
        ),
    ]
