# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandmanager', '0003_song_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='label',
        ),
        migrations.AddField(
            model_name='song',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProgressMapping',
        ),
    ]
