# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandmanager', '0004_auto_20161230_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='picture_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='picture_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
