# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandmanager', '0006_auto_20170108_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bandmanager.Member'),
        ),
    ]
