# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandmanager', '0008_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=200)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandmanager.Band')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='progress',
        ),
        migrations.AddField(
            model_name='song',
            name='learned',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='picture_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='single',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bandmanager.Album'),
        ),
    ]
